import * as XLSX from "xlsx";
import type { Response } from "express";

interface ExcelFileOptions {
  filename: string;
  sheetName: string;
  title?: string;
  subject?: string;
  author?: string;
  company?: string;
}

/**
 * Generates and sends a secure Excel file with proper metadata and security headers
 * to prevent antivirus false positives
 */
export function sendSecureExcelFile(
  res: Response,
  data: any[],
  options: ExcelFileOptions
): void {
  try {
    // Create worksheet from data
    const worksheet = XLSX.utils.json_to_sheet(data);
    
    // Create workbook with proper metadata
    const workbook = XLSX.utils.book_new();
    
    // Add comprehensive file properties to make it look like a legitimate Office document
    workbook.Props = {
      Title: options.title || options.filename,
      Subject: options.subject || "Business Data Export",
      Author: options.author || "RECOV System",
      Company: options.company || "WIZONE IT NETWORK INDIA PVT LTD",
      CreatedDate: new Date(),
      ModifiedDate: new Date(),
      Application: "Microsoft Excel",
      Manager: "RECOV Administrator",
      Category: "Business Reports",
      Keywords: "business, export, data",
      Comments: "Generated by RECOV - Business Management System",
    };
    
    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(workbook, worksheet, options.sheetName);
    
    // Write buffer with proper Excel options
    const buffer = XLSX.write(workbook, {
      type: "buffer",
      bookType: "xlsx",
      compression: true, // Enable compression for smaller, more standard files
      bookSST: false, // Disable shared string table for better compatibility
    });
    
    // Set comprehensive security headers
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", `attachment; filename="${options.filename}"`);
    res.setHeader("Content-Length", buffer.length.toString()); // Exact file size for validation
    res.setHeader("X-Content-Type-Options", "nosniff"); // Prevent MIME sniffing
    res.setHeader("Cache-Control", "private, max-age=0, no-cache, no-store, must-revalidate"); // Security
    res.setHeader("Pragma", "no-cache"); // HTTP 1.0 compatibility
    res.setHeader("Expires", "0"); // Proxies
    res.setHeader("Content-Security-Policy", "default-src 'none'"); // No script execution
    res.setHeader("X-Frame-Options", "DENY"); // Prevent clickjacking
    
    // Send the buffer
    res.send(buffer);
  } catch (error: any) {
    throw new Error(`Failed to generate Excel file: ${error.message}`);
  }
}

/**
 * Creates a secure Excel workbook from multiple sheets
 */
export function createSecureWorkbook(
  sheets: Array<{ data: any[]; sheetName: string }>,
  metadata?: Partial<XLSX.Properties>
): XLSX.WorkBook {
  const workbook = XLSX.utils.book_new();
  
  // Add comprehensive file properties
  workbook.Props = {
    Title: metadata?.Title || "Business Data Export",
    Subject: metadata?.Subject || "Business Data Export",
    Author: metadata?.Author || "RECOV System",
    Company: metadata?.Company || "WIZONE IT NETWORK INDIA PVT LTD",
    CreatedDate: new Date(),
    ModifiedDate: new Date(),
    Application: "Microsoft Excel",
    Manager: "RECOV Administrator",
    Category: "Business Reports",
    Keywords: "business, export, data",
    Comments: "Generated by RECOV - Business Management System",
    ...metadata,
  };
  
  // Add all sheets
  for (const sheet of sheets) {
    const worksheet = XLSX.utils.json_to_sheet(sheet.data);
    XLSX.utils.book_append_sheet(workbook, worksheet, sheet.sheetName);
  }
  
  return workbook;
}

/**
 * Sends a workbook as a secure Excel file
 */
export function sendSecureWorkbook(
  res: Response,
  workbook: XLSX.WorkBook,
  filename: string
): void {
  try {
    // Write buffer with proper Excel options
    const buffer = XLSX.write(workbook, {
      type: "buffer",
      bookType: "xlsx",
      compression: true,
      bookSST: false,
    });
    
    // Set comprehensive security headers
    res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
    res.setHeader("Content-Length", buffer.length.toString());
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Cache-Control", "private, max-age=0, no-cache, no-store, must-revalidate");
    res.setHeader("Pragma", "no-cache");
    res.setHeader("Expires", "0");
    res.setHeader("Content-Security-Policy", "default-src 'none'");
    res.setHeader("X-Frame-Options", "DENY");
    
    res.send(buffer);
  } catch (error: any) {
    throw new Error(`Failed to send Excel file: ${error.message}`);
  }
}
